### ISSUE TITLE
Merge the no_std feature to main, so it's accesible from crates.io

### ISSUE THREAD

**Issue by NexusXe** [thombles/ax25-rs#7]
I'm not sure how you're implementing no_std, but as of right now it's unable to be used from crates.io.

**Comment by thombles** [comment]
Sorry for the slow reply, I forgot I had that branch lingering. I've merged it now and published 0.3 on crates.io. Only the core packet parsing is available under `no_std` and the rest of the TNC functionality is now under a second crate `ax25_tnc`.
